language: java
jdk: oraclejdk11
before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get install -qqy --force-yes linux-image-extra-$(uname -r) apparmor
  - sudo apt-get install -qqy --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine=${DOCKER_ENGINE_VERSION}\*
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose --version
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- sh script/generate_cert.sh
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=guvense_Mahallem-Backend
sudo: required
services:
- docker
addons:
  sonarcloud:
    organization: guvense
    token: $SONAR_TOKEN
after_success:
- bash <(curl -s https://codecov.io/bash)
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin  
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=guvense/mahallem_api
- sh set_pass.sh
- docker-compose build
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
- export IMAGE_NAME_HUB=guvense/mahallem_hub
- docker build -t $IMAGE_NAME_HUB:$COMMIT -f DockerfileHub .
- docker tag $IMAGE_NAME_HUB:$COMMIT $IMAGE_NAME_HUB:$TAG
- docker push $IMAGE_NAME_HUB
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- heroku auth:token
- heroku container:login
- docker tag $IMAGE_NAME registry.heroku.com/mahallem/web
- docker push registry.heroku.com/mahallem/web
- heroku container:release web -a mahallem
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}