language: java
jdk: oraclejdk11
script:
- "./mvnw clean install -B"
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=guvense_Mahallem-Backend
sudo: required
services:
- docker
addons:
  sonarcloud:
    organization: guvense
    token:
      secure: $SONAR_TOKEN
after_success:
- docker login -u "DWgRI4RubtIVHaQCJEqa6vVxojMuidxrYDiol7CemaulcQ4sIHVoDOBqFGoca2H5fM8QF9ApmFg5v6huqczWTuahR7GLlcmwzKr9Gv3g9u/7u1sxZyzeJSHaFZvs7FB6H959NM7ydBMJ7SocrNqXsndaA2lN8LONZyjaukTsQ39vi90gOa4EMzu5MHRlndrHYZEWmt5LerHjM6j3tXrIL6Y08tqTZSDjBNoIX3WkIt4FtyyZstkkIaE/BFWxFYUT6m6otpSXv9kBwKVhIcpZtDZcwI8/b0qMPQn83rUSpiLMSmn6V+Phr+secf2mi9SKgGh+chD3YW5LSl7G6aOIkVAbkrv+hsYq1eg1ApBkDoLFRh1za7nSdqV61cl77rrrYjV3EABrN6gjjOCI03jYjMRhz4NLzsEd8/UfI0YQNP37E2XkER0DsSjrBYCzanGPEoVNadKjQ4y/layzzhMbHCBeXoJ0RTPTNW7wJaoQTPvbZt+h1jcjVzCSt9jtLr2iurbJmqCr3cqU2yuQHGEHvO1mKKKGsurmQ6aBkYPmMfkGXPeX6+Ur5qat2AEL8NNfKq9wgTWDB/FtX42rM9wnElQL6k0dcC2vS/e+U+xsLhNzv8RRgdT7QdPaRjsbbIDvrCxCw6bHTMhC2DDgt9fDbnK6TwnhZ76D9w5Ab9mCErY="
  -p "hq/ni0Lki4kWO7WVmpxk6Nmjm+K3Der3eU8PTUipjc7wgh0hzQ49cq0Uh86TpausMHJZkpx7F3MiazwIAfSvAcNBkKMlEpTn/ax8ofoWh5xvrKOEelKo+J3+nsx0yaHenIgl5h0cfQP17ZelE4zn4UinufVthxZj/d2sy0GR2qgytzhPjifamUxQ6suyfhkSMRwpY6nx5QUYczeosyPdnO9aoIkvudQP/CByl+/5cOsDwgYcf1+xKQRlRPvFLWnK6j+0V7W95WY2e+xsGyA2RwkkcXO9mB/3hwpXcnZLEhbC8iDxdBaD2YH1fpiLUlZFnzxU+I6CfzvFC+FzPPVaGbsLDq6xft/iJdTmUoXhA15jukYd/jJhpXzF2TYM8gpLFve/dVGTK7/s0rqIjBBs+g8pP0n1VYMFdvft2M9afbXVfioSZBAWPh9MBD8XVKb7AZLd/NtXUab4qQ+Yohl8bFOUNK9wkmlDHXa47XClfsV/0Jwipl1w4EK83ltnWt/nLhZcTgiGAslKKkRg4uQ35pSdm6itUnqb9t1wOIPeINrtS/Lr4sUVXiQUm2OlJKH0ME4B74OzwCOL+lIxquyiPEn9ZymPIi6WAfyjf4fi85V9a3a65lkeOo2iYjFC8518PuOKprfR56g72UWAJOaabpVyD8apb0hUFuDh9HaZjW0="
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=guvense/mahallem
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
env:
  global:
    secure: SGn1PdFM430RMXKhxUumkacFjhyxs2YXOLLbWbjk5tL8xAro7alrZ8ql1hLbeD9j+AGrPphj0dnnn7TmkE4+OCKvJK3C3HmBh8An+kEbF255bdNu6kTkc7bW1dow1Rs7DiOhf4Qvg+RVawfg7nkiwvtqfUP5WvAgT4V4IcuKskQmWQqKr01Ndm0ibR+Is98NPfxvXeMOQr1atjuRqy1aTvhmNCi89aFECeu9m9mcJalf/wFexZHezV9s1AXuPG2xCZCPxSXLlN8zMP9IpH+S2LNOOXOC9GChCOA4y0rLhrgGmPmu0XzJLst1blJoTaYwP4T4sytaQlc5Q45VnyY6/unzErhPbLZk9Rnpk/IwOTrRtx1RUr0fkPlY2Ig/szDGP3ChqtwQ9/RX972pEal6Ab8ZfU/BqYDYVM5xRPvx1zyApSNSRBV1hQUr1nyWGpTt5PyDeXRyiaT22sexaXJ6OgFU2EiHQ+Zp9trBV865uCnW0eLVqX9ocdHJFUAmMo0ckkofxRizrZ/j79C3G1aulWw+w4G3ukF7RR/B+pYoyz0FO5rHWPP0k0r9VqtOLhmwivXROBed28/GuEyvftbWJGQ/59F9fIwVQ9ygFNJsY4rZA2bt0eYFRKsCWZA8ycQ5RKFYukYN772Tp4ZTQNwv41K0/os3QI+1IwgbLWcSShc=
