language: java
jdk: oraclejdk11
script:
  -  ./mvnw clean install -B
  -  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=guvense_Mahallem-Backend
env:
  - SONAR_TOKEN="YyDtBuvt0uVKYD+NB/JcGvB7kEdKXUxXOyPm2FDsbX/Jqb5gzPxtxddL1kmm5qCnssMwFEsLrNmnDXorMLUprISHFxE3BeTnMh7ePpcGWbLJDVdj1xrnMgOiGFyr3LSS4m6rWHTHNeg4+O+ziJRg+/I76WUBo4yuAF4+BSiTDhViXytcklJP2nqXKQCKLPxgC3Zf3gi4tXBr+izOjVxojFuFDY5yQ2c1EogjXKc3i1bafaP2kJNKUPTGa5ROI1l/BeMdvIyEzJDvqBgHyQDqb7hnrlpM9rPnSSE8EiIHDHP7WspNGVaWkv/g3ZTXt8mttRpFIMkEaq8fEXGqFfyi85eYU08o83lDOWe4ZqamfZW1BUe9DQZU1gsHkX0BhWkl5YWGKurR4l4UQsxkG1AvbOy53JWyxt/YUzHLOEAieHHj2dgG6xDxaSomIjJuXRMH+D8xfYyUnY2hxRb5U4JbBIBoWqdTQqXAZ4pUJ8cCV7EpIdV5xK5ToCH1hRgOkifDKpFQFK1/aRYbBVh43k8OfSnSjr86LDMEcegrSqvQdjqANmruUK33OHmcUidiBZshcZ460caq379qIcnR9vN1DLSNiu8A4pv+fwUHwGFqOP7mZeNFXmVMO9yjZ4zLQigIBtFofbfExOeW0lijRcBntd2UBrEAzWYzTmVeWoxJwao="
addons:
  sonarcloud:
    organization: "guvense"
    token:
      secure:  $SONAR_TOKEN