language: java
jdk: oraclejdk11
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- sh script/generate_cert.sh
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=guvense_Mahallem-Backend
sudo: required
services:
- docker
addons:
  sonarcloud:
    organization: guvense
    token: $SONAR_TOKEN
after_success:
- bash <(curl -s https://codecov.io/bash)
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin  
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=guvense/mahallem_api
- export IMAGE_NAME_HUB=guvense/mahallem_hub
- sh set_pass.sh
- docker-compose --version
- docker-compose build
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
- docker tag $IMAGE_NAME_HUB:$COMMIT $IMAGE_NAME_HUB:$TAG
- docker push $IMAGE_NAME_HUB
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then sh deploy.sh; fi`

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}