language: java
jdk: oraclejdk11
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- sh script/generate_cert.sh
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=guvense_Mahallem-Backend
sudo: required
services:
- docker
addons:
  sonarcloud:
    organization: guvense
    token: $SONAR_TOKEN
after_success:
- bash <(curl -s https://codecov.io/bash)
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin  
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=guvense/mahallem_api
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
- export IMAGE_NAME_HUB=guvense/mahallem_hub
- docker build -t $IMAGE_NAME_HUB:$COMMIT -f DockerfileHub .
- docker tag $IMAGE_NAME_HUB:$COMMIT $IMAGE_NAME_HUB:$TAG
- docker push $IMAGE_NAME_HUB
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  script:
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
    - docker push $IMAGE_NAME
   
  on:
    branch: master
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}