spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Mahallem
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300
  redis:
    host: localhost
    port: 6379
  azure:
    blob:
      store:
        connectionString: ${azure_blob_store_connection_string}
        containerName: ${azure_blob_store_connectionName}
server:
  port: 8081
