spring:
  data:
    mongodb:
      uri: mongodb://user:${MONGODB_PASS}@ds213645.mlab.com:13645/heroku_048b24zs

    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300
  redis:
    url: redis://h:${REDIS_PASS}@ec2-34-254-83-127.eu-west-1.compute.amazonaws.com:8869

