spring:
  data:
    mongodb:
      uri: mongodb://user:G100545460@ds213645.mlab.com:13645/heroku_048b24zs

    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300
  redis:
    host: localhost
    port: 6379
server:
  port: 80
